{
 "title": "Sagecom",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "query": {
     "query": "label_values(sagemcom_device_status,hostname)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "sagecom api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Router Information",
   "type": "stat",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sagemcom_modem_info_info", "legendFormat": "__auto" },
    { "expr": "public_ip_info_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sagemcom_device_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Devices conntected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Devices" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (interface) (sagemcom_device_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reboot count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sagemcom_device_reboot_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active devices over time",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sagemcom_connected_devices", "legendFormat": "Active devices" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sagemcom_wifi_radio_channel", "legendFormat": "{{radio_index}}" }
   ]
  },
  {
   "title": "Active devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "sagemcom_device_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disconnected devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "expr": "sagemcom_device_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active devices",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "sagemcom_device_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disconnected devices",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "sagemcom_device_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Port mapning",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "targets": [
    { "expr": "sagemcom_port_mappings", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "internet_speedtest_download_mbps",
     "legendFormat": "Download speed"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "internet_speedtest_upload_mbps", "legendFormat": "Upload speed" }
   ]
  },
  {
   "title": "Download speed",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "internet_speedtest_download_mbps",
     "legendFormat": "Download speed"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    { "expr": "internet_speedtest_upload_mbps", "legendFormat": "Download speed" }
   ]
  },
  {
   "title": "Ping to google.dk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ping" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "google_ping_ms", "legendFormat": "Ping" }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ping" } },
   "targets": [
    { "expr": "google_ping_ms", "legendFormat": "Ping" }
   ]
  },
  {
   "title": "Active devices",
   "type": "status-history",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 66 },
   "targets": [
    { "expr": "sagemcom_device_status", "legendFormat": "{{name}}" }
   ]
  }
 ]
}